### ISSUE TITLE
is there demo result for compression restoration (g^-1)

### ISSUE THREAD

**Issue by wl3b10s** [yang-jin-hai/SAIN#2]
is there a demo result for compression restoration (g^-1)?

thanks

**Comment by yang-jin-hai** [comment]
We use $g^{-1}$ and $f^{-1}$ as a whole during our experiments, and havn't try to seprerate the two steps to investigate the compression restoration results. This is a good point, you can have a try and welcome to post some results here.

**Comment by wl3b10s** [comment]
> We use g−1g−1g^{-1} and f−1f−1f^{-1} as a whole during our experiments, and havn't try to seprerate the two steps to investigate the compression restoration results. This is a good point, you can have a try and welcome to post some results here.

so there is no loss function and label to constrain the input of g and output of g^-1.   
Is my understanding correct?

**Comment by yang-jin-hai** [comment]
Not exactly, you can read Section 3.3 LR guidance for details. We made some constraints on $g$ and $g^{-1}$, but did not try to visualize the compression-restored results (i.e., $y_r$)。

**Comment by wl3b10s** [comment]
understood thanks.
